import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect } from 'react'
import { getURL } from 'next/dist/shared/lib/utils';

export default function Home() {
  useEffect(() => {
    const currentURL = `http://localhost:3000${getURL()}`;
    console.log(currentURL);
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        Hello worlds!
      </main>
    </>
  )
}
